# Generated by Django 4.2.29 on 2026-03-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aggregation', models.IntegerField(choices=[(1, 'Mean of grades'), (2, 'Weighted mean of grades'), (3, 'Simple weighted mean'), (4, 'Lowest grade'), (5, 'Highest grade'), (6, 'Sum of grades'), (13, 'Natural weighting')], default=13)),
                ('keeps_high', models.IntegerField(default=0)),
                ('drop_low', models.IntegerField(default=0)),
                ('aggregation_coeff', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('aggregation_coeff_extra', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('depth', models.IntegerField(default=2)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='courses.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='grades.gradecategory')),
            ],
            options={
                'verbose_name': 'Grade Category',
                'verbose_name_plural': 'Grade Categories',
                'db_table': 'elening_grade_categories',
            },
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('course', 'Course total'), ('category', 'Category total'), ('manual', 'Manual grade'), ('mod', 'Activity module')], default='mod', max_length=30)),
                ('item_module', models.CharField(blank=True, max_length=30)),
                ('item_instance', models.IntegerField(blank=True, null=True)),
                ('grade_max', models.DecimalField(decimal_places=5, default=100, max_digits=10)),
                ('grade_min', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('grade_pass', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('weight_override', models.BooleanField(default=False)),
                ('aggregation_coeff', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('aggregation_coeff_extra', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('display', models.IntegerField(default=0)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('hidden', models.IntegerField(default=0)),
                ('locked', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('locktime', models.IntegerField(default=0)),
                ('needsupdate', models.IntegerField(default=0)),
                ('sortorder', models.IntegerField(default=1)),
                ('outcomeid', models.IntegerField(blank=True, null=True)),
                ('scaleid', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_items', to='grades.gradecategory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to='courses.course')),
            ],
            options={
                'db_table': 'elening_grade_items',
                'ordering': ['sortorder'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_grade', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('raw_grade_max', models.DecimalField(decimal_places=5, default=100, max_digits=10)),
                ('raw_grade_min', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('raw_scale_id', models.IntegerField(blank=True, null=True)),
                ('finalgrade', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('hidden', models.IntegerField(default=0)),
                ('locked', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('locktime', models.IntegerField(default=0)),
                ('exported', models.IntegerField(default=0)),
                ('overridden', models.IntegerField(default=0)),
                ('excluded', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('feedbackformat', models.IntegerField(default=1)),
                ('information', models.TextField(blank=True)),
                ('informationformat', models.IntegerField(default=0)),
                ('timecreated', models.IntegerField(blank=True, null=True)),
                ('timemodified', models.IntegerField(blank=True, null=True)),
                ('aggregationstatus', models.CharField(default='unknown', max_length=10)),
                ('aggregationweight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.gradeitem')),
            ],
            options={
                'db_table': 'elening_grades',
            },
        ),
    ]
