# Generated by Django 4.2.29 on 2026-03-05 16:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('fraction', models.DecimalField(decimal_places=5, default=0, help_text='1.0 = correct, 0.0 = wrong, negative for penalty', max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('sortorder', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'elening_answers',
                'ordering': ['sortorder'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multichoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer'), ('numerical', 'Numerical'), ('essay', 'Essay'), ('matching', 'Matching'), ('ddwtos', 'Drag and drop into text')], default='multichoice', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('general_feedback', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('default_mark', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.3333333, help_text='Fraction deducted per wrong attempt (for multiple tries)', max_digits=6)),
                ('sortorder', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_questions',
                'ordering': ['sortorder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True)),
                ('fraction', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_question_responses',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Instructions')),
                ('time_open', models.DateTimeField(blank=True, help_text='Quiz opens at', null=True)),
                ('time_close', models.DateTimeField(blank=True, help_text='Quiz closes at', null=True)),
                ('time_limit', models.IntegerField(default=0, help_text='Time limit in seconds, 0=unlimited')),
                ('grade', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('attempts_allowed', models.IntegerField(default=1, help_text='-1 = unlimited')),
                ('grade_method', models.IntegerField(choices=[(1, 'Highest grade'), (2, 'Average grade'), (3, 'First attempt'), (4, 'Last attempt')], default=1)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('questions_per_page', models.IntegerField(default=0, help_text='0 = all on one page')),
                ('show_user_picture', models.BooleanField(default=False)),
                ('decimal_points', models.IntegerField(default=2)),
                ('show_blocks', models.BooleanField(default=False)),
                ('pass_grade', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'db_table': 'elening_quizzes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('inprogress', 'In Progress'), ('overdue', 'Overdue'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='inprogress', max_length=16)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_finish', models.DateTimeField(blank=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('sumgrades', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('layout', models.TextField(blank=True, help_text='Comma-separated question IDs in page order')),
                ('current_page', models.IntegerField(default=0)),
                ('preview', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'elening_quiz_attempts',
                'ordering': ['-time_start'],
            },
        ),
    ]
