# Generated by Django 4.2.29 on 2026-03-05 16:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=254, verbose_name='Full Name')),
                ('shortname', models.CharField(max_length=255, unique=True, verbose_name='Short Name')),
                ('idnumber', models.CharField(blank=True, max_length=100)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Course Summary')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('format', models.CharField(choices=[('topics', 'Topics format'), ('weeks', 'Weekly format'), ('social', 'Social format'), ('singleactivity', 'Single activity format')], default='topics', max_length=21)),
                ('enrollment_type', models.CharField(choices=[('open', 'Open enrollment'), ('manual', 'Manual enrollment'), ('paid', 'Paid enrollment'), ('invite', 'Invitation only')], default='open', max_length=20)),
                ('enrolment_key', models.CharField(blank=True, help_text='Enrollment key/password', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('visible', models.BooleanField(default=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=30)),
                ('theme', models.CharField(blank=True, max_length=50)),
                ('max_students', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('completion_enabled', models.BooleanField(default=False)),
                ('show_grades', models.BooleanField(default=True)),
                ('show_activity_dates', models.BooleanField(default=True)),
                ('news_items', models.IntegerField(default=5)),
                ('sortorder', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'elening_courses',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idnumber', models.CharField(blank=True, max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('sortorder', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('depth', models.IntegerField(default=1)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('theme', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'elening_course_categories',
                'ordering': ['sortorder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(default=0, help_text='Section number (0=general)')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('availability', models.TextField(blank=True)),
                ('sortorder', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'db_table': 'elening_course_sections',
                'ordering': ['sortorder', 'section'],
            },
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('display', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='courses.course')),
            ],
            options={
                'db_table': 'elening_course_pages',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('page', 'Page'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('forum', 'Forum'), ('file', 'File'), ('url', 'URL'), ('label', 'Label/Text'), ('video', 'Video'), ('scorm', 'SCORM Package')], max_length=20)),
                ('instance_id', models.PositiveIntegerField(blank=True, help_text='FK to the specific activity table (quiz, assignment, etc.)', null=True)),
                ('name', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('sortorder', models.IntegerField(default=0)),
                ('indent', models.IntegerField(default=0)),
                ('completion', models.IntegerField(default=0)),
                ('completion_view', models.BooleanField(default=False, help_text='Complete on view')),
                ('availability', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.coursesection')),
            ],
            options={
                'db_table': 'elening_course_modules',
                'ordering': ['section__sortorder', 'sortorder'],
            },
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='course_files/')),
                ('display', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course')),
            ],
            options={
                'db_table': 'elening_course_files',
            },
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inprogress', 'In Progress'), ('complete', 'Completed'), ('completedpass', 'Completed (Pass)'), ('completedfail', 'Completed (Fail)')], default='inprogress', max_length=20)),
                ('timecompleted', models.DateTimeField(blank=True, null=True)),
                ('reaggregate', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.course')),
            ],
            options={
                'db_table': 'elening_course_completions',
            },
        ),
    ]
