# Generated by Django 4.2.29 on 2026-03-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrollment_type',
            field=models.CharField(choices=[('open', 'Open enrollment'), ('manual', 'Manual enrollment (teacher approves)'), ('invite', 'Invitation only')], default='open', max_length=20),
        ),
    ]
