# Generated by Django 4.2.29 on 2026-03-05 16:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('intro_attachments', models.FileField(blank=True, null=True, upload_to='assignment_intros/')),
                ('submission_type', models.CharField(choices=[('onlinetext', 'Online text'), ('file', 'File upload'), ('both', 'Online text & file')], default='file', max_length=20)),
                ('grading_method', models.CharField(choices=[('simple', 'Simple direct grading'), ('rubric', 'Rubric'), ('guide', 'Marking guide')], default='simple', max_length=20)),
                ('max_grade', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('passing_grade', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('allow_submissions_from', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('cut_off_date', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=-1, help_text='-1 = unlimited')),
                ('max_files', models.IntegerField(default=1)),
                ('max_file_size', models.IntegerField(default=0, help_text='Max size in bytes, 0=unlimited')),
                ('allowed_file_types', models.CharField(blank=True, help_text='e.g. .pdf,.docx', max_length=255)),
                ('team_submission', models.BooleanField(default=False)),
                ('require_submission_statement', models.BooleanField(default=False)),
                ('blind_marking', models.BooleanField(default=False)),
                ('send_late_notifications', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_assignments',
                'ordering': ['due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feedback', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('released', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'elening_assignment_grades',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reopened', 'Reopened')], default='draft', max_length=20)),
                ('online_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('attempt_number', models.IntegerField(default=0)),
                ('latest', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
            ],
            options={
                'db_table': 'elening_submissions',
                'ordering': ['-modified_at'],
            },
        ),
    ]
