# Generated by Django 4.2.29 on 2026-03-05 16:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('forum_type', models.CharField(choices=[('general', 'General discussion'), ('news', 'News and announcements'), ('single', 'Single simple discussion'), ('qanda', 'Q & A forum'), ('blog', 'Blog-like forum')], default='general', max_length=20)),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('assessed', models.IntegerField(default=0)),
                ('scale', models.IntegerField(default=0)),
                ('max_bytes', models.IntegerField(default=0)),
                ('max_attachments', models.IntegerField(default=1)),
                ('force_subscribe', models.IntegerField(default=0)),
                ('tracking_type', models.IntegerField(default=1)),
                ('rss_type', models.IntegerField(default=0)),
                ('rss_articles', models.IntegerField(default=0)),
                ('block_after', models.IntegerField(default=0)),
                ('block_period', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_forums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='forum_attachments/')),
                ('edited', models.BooleanField(default=False)),
                ('mailed', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_forum_posts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_read', models.DateTimeField(auto_now_add=True)),
                ('last_read', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_forum_reads',
            },
        ),
        migrations.CreateModel(
            name='ForumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'elening_forum_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subject')),
                ('pinned', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_forum_threads',
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
    ]
