# Generated by Django 4.2.29 on 2026-03-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('conv_type', models.IntegerField(choices=[(1, 'Individual'), (2, 'Group')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='conversation_images/')),
                ('component', models.CharField(blank=True, max_length=100)),
                ('item_type', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('context_id', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('muted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elening_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elening_conversation_members',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('full_message', models.TextField()),
                ('full_message_html', models.TextField(blank=True)),
                ('full_message_format', models.IntegerField(default=1)),
                ('small_message', models.TextField(blank=True)),
                ('notification', models.BooleanField(default=False)),
                ('context_url', models.URLField(blank=True)),
                ('context_url_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_sender', models.BooleanField(default=False)),
                ('custom_data', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'elening_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='messaging.message')),
            ],
            options={
                'db_table': 'elening_message_reads',
            },
        ),
    ]
